# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
name: "Extracts release branches"
description: "Extracts the relevant release branches from Flink's git checkout."
outputs:
  newest_release:
    description: "The release branch of the most-recently released Flink minor version."
    value: ${{ steps.release_branch_extraction_step.outputs.newest_release }}
  penultimate_release:
    description: "The release branch belonging to the release that preceded the most-recent Flink minor release."
    value: ${{ steps.release_branch_extraction_step.outputs.penultimate_release }}
  antepenultimate_release:
    description: "The most-recent Flink minor release that reached end-of-live support."
    value: ${{ steps.release_branch_extraction_step.outputs.antepenultimate_release }}
runs:
  using: "composite"
  steps:
    - name: "Extracts release branches"
      id: release_branch_extraction_step
      shell: bash
      run: |
        # fetch branch information first
        git fetch origin
        
        release_branches_ordered_by_version="$(git branch -r | grep origin | grep -o '[^/]*$' | grep 'release-[1-9]\.[0-9]*$' | sort --field-separator '-' --key 2V)"
        
        newest_release_branch="$(echo $release_branches_ordered_by_version | tr ' ' '\n' | tail -1 | head -1)"
        penultimate_release_branch="$(echo $release_branches_ordered_by_version | tr ' ' '\n' | tail -2 | head -1)"
        antepenultimate_release_branch="$(echo $release_branches_ordered_by_version | tr ' ' '\n' | tail -3 | head -1)"

        echo "Extracted release branches:"
        echo "    Branch of newest release: ${newest_release_branch}"
        echo "    Branch of release that preceded the newest release: ${penultimate_release_branch}"
        echo "    Branch of that got deprecated most-recently: ${antepenultimate_release_branch}"
        
        echo "newest_release=${newest_release_branch}" >> ${GITHUB_OUTPUT}
        echo "penultimate_release=${penultimate_release_branch}" >> ${GITHUB_OUTPUT}
        echo "antepenultimate_release=${antepenultimate_release_branch}" >> ${GITHUB_OUTPUT}
